# File: .github/workflows/ci.yml
name: CI/CD Pipeline

permissions:
  contents: read
  actions: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'     # esecuzione notturna alle 03:00 UTC
  workflow_dispatch:       # “Run workflow” manuale

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: modulo-ia-core:ci-latest


