# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Imposta Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Installa dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # 4) Linting con flake8 (ignora le regole E203,E231,E302,E501,F841,W391 per il momento)
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 modules run_ai.py scripts \
            --max-line-length=120 \
            --ignore=E203,E231,E302,E501,F841,W391

      # 5) Esegui i test (se li hai)
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # 6) Build dell’immagine Docker (non push)
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: modulo-ia-core:ci-latest
