name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Installa dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Linting con flake8
      #    Ignora temporaneamente i codici E402, E303, E221 fino a che non rifattori
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 \
            --max-line-length=120 \
            --ignore=E203,E221,E231,E302,E303,E402,E501,F841,W391 \
            modules run_ai.py scripts

      # 5) Esegui i test con pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # 6) Build dell’immagine Docker (senza push)
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: modulo-ia-core:ci-latest
