# File: .github/workflows/evaluate_and_deployer.yml
name: Evaluate & Deploy Model

permissions:
  contents: read    # per checkout del repo
  actions: write    # per upload/download-artifact

on:
  workflow_run:
    workflows: ["Nightly Model Training"]
    types: [completed]
  workflow_dispatch:  # facoltativo, per trigger manuale

jobs:
  evaluate:
    name: Evaluate Model
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download trained model
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: models

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Evaluate model
        run: |
          python scripts/evaluate_model.py \
            --model-dir models \
            --data-dir data/processed

      - name: Upload evaluation metrics
        uses: actions/upload-artifact@v2
        with:
          name: evaluation-metrics
          path: models/metrics.json

  deploy:
    name: Conditional Deploy
    needs: evaluate
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.evaluate.outputs.accuracy) > fromJson(needs.evaluate.outputs.previous_accuracy) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download trained model
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: models

      - name: Deploy to production
        run: |
          python scripts/deploy_model.py \
            --model-path models/model.h5
