# File: .github/workflows/evaluate_and_deployer.yml
name: Evaluate & Deploy Model

# Permessi necessari per checkout e artifact
permissions:
  contents: read     # per checkout del codice
  actions: write     # per download-artifact e upload-artifact
  packages: write    # se usi packages (opzionale)

# Trigger: dopo il successo del training notturno
on:
  workflow_run:
    workflows: ["Nightly Model Training"]
    types: [completed]
  workflow_dispatch: # per test manuale

jobs:
  evaluate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download trained model
        uses: actions/download-artifact@v3
        name: Download trained model
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: models

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Evaluate model
        run: |
          python scripts/evaluate_model.py \
            --model-dir models \
            --data-dir data/processed

      - name: Upload metrics
        uses: actions/upload-artifact@v3
      - name: Upload metrics
        uses: actions/upload-artifact@v2
        with:
          name: metrics
          path: models/metrics.json

  deploy:
    needs: evaluate
    runs-on: ubuntu-latest
    # esegui il deploy solo se l'accuracy è migliorata
    if: ${{ fromJson(needs.evaluate.outputs.metrics).accuracy > fromJson(needs.evaluate.outputs.metrics_old).accuracy }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download trained model
        uses: actions/download-artifact@v3
      - name: Download trained model
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: models

      - name: Deploy model to production
        run: |
          python scripts/deploy_model.py \
            --model-path models/model.h5

