# .github/workflows/nightly_training.yml
name: Nightly Model Training

permissions:
  contents: read
  actions: write
  packages: write

on:
  schedule:
    - cron: '30 04 * * *'    # ogni giorno alle 04:30 UTC
  workflow_dispatch:

jobs:
  train:
    name: Train Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download processed data
        uses: actions/download-artifact@v3
        with:
          name: processed-data
          path: data/processed

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training
        run: |
          python scripts/train_model.py \
            --data-dir data/processed \
            --out-dir  models

      - name: Upload trained model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/**

