# File: .github/workflows/nightly_metrics_ingestion.yml
name: Nightly Metrics Ingestion

<<<<<<< HEAD
# Permessi minimi per checkout e artifact
permissions:
  contents: read      # per actions/checkout
  actions: write      # per upload/download-artifact
  packages: write     # se usi GitHub Package Registry (opzionale)
=======
permissions:
  contents: read      # per checkout del codice
  actions:  write     # per upload/download-artifact
  packages: write     # se usi package registry (opzionale)
>>>>>>> 1512be1 (Fix GH Actions: switch upload/download-artifact to @v2)

on:
  schedule:
    - cron: '0 2 * * *'    # ogni giorno alle 02:00 UTC
  workflow_dispatch:      # abilita il pulsante “Run workflow” manuale

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      DB_HOST:     ${{ secrets.DB_HOST }}
      DB_PORT:     ${{ secrets.DB_PORT }}
      DB_NAME:     ${{ secrets.DB_NAME }}
      DB_USER:     ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run metrics ingestion
        run: |
          python -m modules.metrics_ingestion \
            --clicks-path      data/clicks.csv \
            --conversions-path data/conversions.csv \
            --revenue-path     data/conversion_report.csv

      - name: Upload metrics artifact
<<<<<<< HEAD
=======
        uses: actions/upload-artifact@v3
      - name: Upload metrics artifact
>>>>>>> 1512be1 (Fix GH Actions: switch upload/download-artifact to @v2)
        uses: actions/upload-artifact@v2
        with:
          name: metrics-report
          path: modules/output/metrics.json


