name: Nightly Data Ingestion

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data ingestion
        run: |
          python scripts/ingest_data.py \
            --input data/raw \
            --output data/processed

      - name: Upload processed-data artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-data
          path: data/processed/
