# File: .github/workflows/nightly_data_ingestion.yml
name: Nightly Data Ingestion

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data ingestion
        run: |
          python scripts/ingest_data.py --input data/raw --output data/processed

      - name: Upload processed data
        uses: actions/upload-artifact@v2
        with:
          name: processed-data
          path: data/processed/
