name: Nightly Metrics Ingestion

# autorizzazioni per upload‑artifact / download‑artifact
permissions:
  contents: read      # per checkout e lettura repo
  actions:  read      # per eseguire altri workflow
  packages: write     # per upload/download artifact

on:
  schedule:
    - cron: '0 2 * * *'  # ogni giorno alle 02:00 UTC
+  workflow_dispatch:    # ← abilita il “Run workflow” manuale
jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Run metrics ingestion
        run: |
          python modules/metrics_ingestion.py \
            --clicks-path data/clicks.csv \
            --conversions-path data/conversions.csv \
            --revenue-path data/conversion_report.csv