name: Nightly Data Ingestion

# autorizzazioni per upload‑artifact / download‑artifact
permissions:
  contents: read      # per checkout e lettura repo
  actions:  read      # per eseguire altri workflow
  packages: write     # per upload/download artifact
  
# 1) Trigger ogni notte alle 02:00 UTC
on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  ingestion:
    runs-on: ubuntu-latest

    steps:
      # 2) Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3) Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Installa dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5) Esegui lo script di ingestion
      - name: Run data ingestion
        run: |
          python scripts/ingest_data.py \
            --input data/raw \
            --output data/processed

      # 6) Salva i dati elaborati come artifact (opzionale)
      - name: Upload processed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/processed/
