# File: .github/workflows/nightly_training.yml
name: Nightly Model Training

permissions:
  contents: read
  actions: write

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download processed data
        uses: actions/download-artifact@v2
        with:
          name: processed-data
          path: data/processed

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training
        run: |
          python scripts/train_model.py \
            --data-dir data/processed \
            --out-dir models

      - name: Upload trained model
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: models/**
