name: Nightly Model Training

# autorizzazioni per upload-artifact / download-artifact
permissions:
  contents: read
  actions:  read
  packages: write

# Trigger ogni notte alle 02:30 UTC + manuale
on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Download dati elaborati
      - name: Download processed data
        uses: actions/download-artifact@v3
        with:
          name: processed-data
          path: data/processed

      # 3) Setup Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Installa dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5) Esegui il training
      - name: Run training
        run: |
          python scripts/train_model.py \
            --data-dir data/processed \
            --out-dir  models

      # 6) Salva modello e metriche
      - name: Upload trained model
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: models/**
