# File: .github/workflows/nightly_data_ingestion.yml
name: Nightly Data Ingestion

# Permessi necessari per checkout e upload/download artifact
permissions:
  contents: read     # per actions/checkout
  actions: write     # per actions/upload/download-artifact

on:
  schedule:
    - cron: '0 2 * * *'   # ogni notte alle 02:00 UTC
  workflow_dispatch:     # abilita il “Run workflow” manuale

jobs:
  ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data ingestion
        run: python scripts/ingest_data.py --input data/raw --output data/processed

      - name: Upload processed data
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: data/processed/
